### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tuttinator** [mileszim/documentcloud#6]
I had a question about whether you would accept a pull request to add tests to this project, and if you had preferences for or against RSpec as a development dependency or Minitest.

Thanks,

Caleb

**Comment by mileszim** [comment]
@tuttinator I will most definitely accept a PR with tests, that would be greatly appreciated. I have no preference for testing suite, so use whichever one works best for you. Thank you!

**Comment by tuttinator** [comment]
Great! I'll start working on it.

**Comment by mileszim** [comment]
Closing in favor of #16
